<?php

use Illuminate\Database\Seeder;

class PartenairesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('partenaires')->insert(['id'=>'1', 'libelle_partenaire'=>'ASCOMA-CAMEROUN', 'b_prive'=>'200', 'adresse'=>'BP 447  YAOUNDE', 'telephone'=>'TEL : 22213055', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'200', 'b_proforma'=>'200', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'2', 'libelle_partenaire'=>'SAAR - KOM ASSURANCES', 'b_prive'=>'150', 'adresse'=>'Yaounde', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'3', 'libelle_partenaire'=>'PERSONNELLE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'4', 'libelle_partenaire'=>'BRASSERIES- &quot; 33 &quot; EXPORT', 'b_prive'=>'150', 'adresse'=>'yaounde', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'5', 'libelle_partenaire'=>'BRASSERIES- &quot; CASTEL BEER&quot;', 'b_prive'=>'150', 'adresse'=>'yaounde', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'6', 'libelle_partenaire'=>'BENEFICIAL GENERAL INSURANCE', 'b_prive'=>'180', 'adresse'=>'Rue LOTTIN SAME BP 2328', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'7', 'libelle_partenaire'=>'SAMARITAN INSURANCES', 'b_prive'=>'0', 'adresse'=>'BP 6230  YAOUNDE', 'telephone'=>'222226247', 'fax'=>'222226248', 'email'=>'S/C nguidjou félicien : tel 75366337 .Resp santé', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'8', 'libelle_partenaire'=>'ALLIANZ - ASSURANCES', 'b_prive'=>'0', 'adresse'=>'BP 105 DLA', 'telephone'=>'Tel:33 50 20 00', 'fax'=>'R.C Douala 4573', 'email'=>'N° de Contribuable : MO 17400000344U', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'260', 'b_proforma'=>'260', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'9', 'libelle_partenaire'=>'ZENITHE-ASSURANCES', 'b_prive'=>'180', 'adresse'=>'yaounde', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'10', 'libelle_partenaire'=>'CENTRE MEDICAL DE RADIOLOGIE ET D\'ECHOGRAPHIE', 'b_prive'=>'150', 'adresse'=>'CEMRE', 'telephone'=>'22 23 85 06', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'11', 'libelle_partenaire'=>'SAAR- ASSURANCES  ( MALADIE )', 'b_prive'=>'180', 'adresse'=>'BP 11834  YAOUNDE', 'telephone'=>'22 20 66 48', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'12', 'libelle_partenaire'=>'DR EBOUMBOU MARIE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'13', 'libelle_partenaire'=>'CHANAS - ASSURANCES', 'b_prive'=>'150', 'adresse'=>'BP 109  DOUALA', 'telephone'=>'TEL  : 33421474', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'14', 'libelle_partenaire'=>'SAMAMEDEQ', 'b_prive'=>'150', 'adresse'=>'carrefour emia', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'15', 'libelle_partenaire'=>'CLINIQUE VERJOSEL ( PR ELOUNDOU NGAH )', 'b_prive'=>'150', 'adresse'=>'yaounde', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'16', 'libelle_partenaire'=>'C M A  MVOG  ADA', 'b_prive'=>'150', 'adresse'=>'YAOUNDE', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'17', 'libelle_partenaire'=>'BEAC - CAMEROUN', 'b_prive'=>'180', 'adresse'=>'yaounde', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'18', 'libelle_partenaire'=>'CABINET  ST MICHEL', 'b_prive'=>'150', 'adresse'=>'yaounde', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'0']);
 DB::table('partenaires')->insert(['id'=>'19', 'libelle_partenaire'=>'SAHAM ASSURANCE', 'b_prive'=>'0', 'adresse'=>'BP 11315  YAOUNDE', 'telephone'=>'TEL : 22222896', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'20', 'libelle_partenaire'=>'CLINIQUE DU BON SECOUR', 'b_prive'=>'150', 'adresse'=>'yaounde', 'telephone'=>'222 22 24 20 -', 'fax'=>'672 15 15 15', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'21', 'libelle_partenaire'=>'CENTRE COMMUNAUTAIRE NGOUSSO', 'b_prive'=>'150', 'adresse'=>'yaounde', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'22', 'libelle_partenaire'=>'GRAS SAVOYE', 'b_prive'=>'180', 'adresse'=>'578 RUE TOBIE KUOH BP 3014 DOUALA  RCCM/DLA/1980/B/007700   N° CONT. M128000000777W', 'telephone'=>'TEL : 33432122', 'fax'=>'', 'email'=>'RCCM/DLA/1980/B/007700', 'site_web'=>'N° CONT. M128000000777W', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'23', 'libelle_partenaire'=>'AXA ASSURANCES', 'b_prive'=>'0', 'adresse'=>'B.P 4068 DOUALA', 'telephone'=>'33423159', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'25', 'libelle_partenaire'=>'NSIA', 'b_prive'=>'0', 'adresse'=>'', 'telephone'=>'22626640', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'26', 'libelle_partenaire'=>'GIZ', 'b_prive'=>'150', 'adresse'=>'YAOUNDE', 'telephone'=>'22211816', 'fax'=>'22219118', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'27', 'libelle_partenaire'=>'CONSTRUCCIONES GALDIANO SA', 'b_prive'=>'150', 'adresse'=>'YAOUNDE', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'28', 'libelle_partenaire'=>'SOSUCAM', 'b_prive'=>'0', 'adresse'=>'BP 857 YAOUNDE', 'telephone'=>'TEL :  22230841', 'fax'=>'22230585', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'29', 'libelle_partenaire'=>'LABORATOIRE DU CENTRE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'222322000', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'30', 'libelle_partenaire'=>'CABINET MEDICAL DE BASTOS', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'31', 'libelle_partenaire'=>'ASSOCIATION  SANTE NATURE (BIG BANG)', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'32', 'libelle_partenaire'=>'LABORATOIRE PRIMA', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'22225375', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'33', 'libelle_partenaire'=>'CENTRE PASTEUR DU CAMEROUN', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'34', 'libelle_partenaire'=>'G T LABO', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'35', 'libelle_partenaire'=>'CAMINSUR', 'b_prive'=>'150', 'adresse'=>'BP 12400  YAOUNDE', 'telephone'=>'TEL : 22225432', 'fax'=>'22714823', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'37', 'libelle_partenaire'=>'SAAR - VIE', 'b_prive'=>'180', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'38', 'libelle_partenaire'=>'SOCIETE NATIONALE DES HYDROCARBURES ( SNH )', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'39', 'libelle_partenaire'=>'ACTIVA  ASSURANCES CAMEROUN', 'b_prive'=>'180', 'adresse'=>'BP 6018 YAOUNDE', 'telephone'=>'22 22 83 72', 'fax'=>'22 23 05 91', 'email'=>'', 'site_web'=>'www.agroupe-activa.com', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'36', 'libelle_partenaire'=>'CABINET  DR NGAMY', 'b_prive'=>'150', 'adresse'=>'YAOUNDE', 'telephone'=>'99510776', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'40', 'libelle_partenaire'=>'CABINET MEDICAL HIPPOCRATE', 'b_prive'=>'150', 'adresse'=>'BP', 'telephone'=>'22 22 87 13', 'fax'=>'74 70 21 20', 'email'=>'', 'site_web'=>'www.allodocteur.cameroun.org', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'41', 'libelle_partenaire'=>'CESARESOMA', 'b_prive'=>'150', 'adresse'=>'MIMBOMAN', 'telephone'=>'222 22 13 61', 'fax'=>'699797979', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'20', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'42', 'libelle_partenaire'=>'SODECOTON', 'b_prive'=>'150', 'adresse'=>'BP 304   YAOUNDE', 'telephone'=>'22 27 10 80', 'fax'=>'RC/GOU/2007/B/7', 'email'=>'N° CONT M057400000146H', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'43', 'libelle_partenaire'=>'CABINET MEDICALE KUM', 'b_prive'=>'150', 'adresse'=>'ETOA MEKI', 'telephone'=>'99 36 17 41', 'fax'=>'KUM ZACHEUS', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'44', 'libelle_partenaire'=>'CLAB LABO - GEOCHIM', 'b_prive'=>'150', 'adresse'=>'ROSTAND', 'telephone'=>'99 99 44 84', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'45', 'libelle_partenaire'=>'TRADEX', 'b_prive'=>'150', 'adresse'=>'BP  1468  DOUALA', 'telephone'=>'33 43 63 75', 'fax'=>'33 43 63 80', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'46', 'libelle_partenaire'=>'TRADEX', 'b_prive'=>'150', 'adresse'=>'BP  1468 DOUALA', 'telephone'=>'33 43 63 75', 'fax'=>'33 43 63 80', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'0']);
 DB::table('partenaires')->insert(['id'=>'47', 'libelle_partenaire'=>'LABOTHERA SARL', 'b_prive'=>'150', 'adresse'=>'BP 2009', 'telephone'=>'99 92 68 52', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'48', 'libelle_partenaire'=>'POLYCLINIQUE DU PALAIS', 'b_prive'=>'150', 'adresse'=>'97766929', 'telephone'=>'75591236', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'49', 'libelle_partenaire'=>'SOCIETE INTERNATIONALE DE TELECOMMUNICATIONS AERONAUTIQUES (S I T A)', 'b_prive'=>'150', 'adresse'=>'232 AVENUE KENNEDY', 'telephone'=>'22 23 49 09', 'fax'=>'', 'email'=>'Yaounde@sita.aero', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'50', 'libelle_partenaire'=>'LAMAT', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'22213040', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'61', 'libelle_partenaire'=>'GMC  ASSURANCES', 'b_prive'=>'0', 'adresse'=>'BP 1965 DOUALA', 'telephone'=>'233432134', 'fax'=>'233432137', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'51', 'libelle_partenaire'=>'PRO ASSUR', 'b_prive'=>'180', 'adresse'=>'BP 5963  DOUALLA', 'telephone'=>'33 43 70 05', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'52', 'libelle_partenaire'=>'ECOBANK CAMEROUN', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'55', 'libelle_partenaire'=>'MDC', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'242067020', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'53', 'libelle_partenaire'=>'LE JOUR', 'b_prive'=>'150', 'adresse'=>'BP 14097  YAOUNDE', 'telephone'=>'22040185', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'40', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'54', 'libelle_partenaire'=>'CABINET MOTAZE ST MICHEL', 'b_prive'=>'150', 'adresse'=>'BP10018  YAOUNDE', 'telephone'=>'222128627 -', 'fax'=>'6787797373', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'25', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'56', 'libelle_partenaire'=>'HOPITAL CENTRAL DE YAOUNDE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'79 36 96 96', 'fax'=>'', 'email'=>'S/C YAOUBA DJAKARY', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'57', 'libelle_partenaire'=>'CENTRE HOSPITALIER ST JOSEPH DE NKOULOU', 'b_prive'=>'150', 'adresse'=>'BP 14666 YDE', 'telephone'=>'TEL: 33711409', 'fax'=>'', 'email'=>'saintjoseph.centrehospitalier@yahoo.fr', 'site_web'=>'responsable labo (mme lako) tel:75591852', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'58', 'libelle_partenaire'=>'CIGNA INTERNATIONAL', 'b_prive'=>'0', 'adresse'=>'BP 69 B-2140 ANVERS - BELGIQUE', 'telephone'=>'003232176965', 'fax'=>'0033149702679', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'170', 'b_proforma'=>'170', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'59', 'libelle_partenaire'=>'HENNER GMC', 'b_prive'=>'0', 'adresse'=>'TUNISIE', 'telephone'=>'0021671113401', 'fax'=>'', 'email'=>'', 'site_web'=>'www.henner.com', 'id_type_partenaire'=>1, 'b_public'=>'170', 'b_proforma'=>'170', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'60', 'libelle_partenaire'=>'LABORATOIRE D\'EFOULAN', 'b_prive'=>'150', 'adresse'=>'EFOULAN LAC', 'telephone'=>'79 50 91 96', 'fax'=>'', 'email'=>'zoti2000@yahoo.fr', 'site_web'=>'Responsable Labo 77 91 49 03', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'25', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'63', 'libelle_partenaire'=>'CENTRE DE PRESTATION SOCIO SANITAIRE D\'INNOVATON', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'94 38 76 12', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'62', 'libelle_partenaire'=>'ASSOCIATION HUMANITAITRE AXES ( ASAXES )', 'b_prive'=>'150', 'adresse'=>'DOUALA', 'telephone'=>'91727270', 'fax'=>'30156672', 'email'=>'studicard@asaxes.org', 'site_web'=>'www.asaxes.org', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'64', 'libelle_partenaire'=>'MTN CAMEROON - 360, RUE DROUOT AKWA.BP 15574 DLA . N° RC/DLA/200/B/025143-N° CONT M 0999800009100C', 'b_prive'=>'150', 'adresse'=>'PO BOX 15574 DOUALA', 'telephone'=>'+237 679009000', 'fax'=>'', 'email'=>'', 'site_web'=>'www.mtncameroon.net', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'65', 'libelle_partenaire'=>'SOSUCAM ( VISITES SYSTEMATIQUES ANNUELLES 2016)', 'b_prive'=>'150', 'adresse'=>'BP 857 YAOUNDÉ', 'telephone'=>'22230585', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'66', 'libelle_partenaire'=>'CAMWATER ( ACENCE CENTRE-SUD- EST )     S/C DR MVOGO GERVAIS', 'b_prive'=>'150', 'adresse'=>'BP 157  DOUALA', 'telephone'=>'33439980', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'67', 'libelle_partenaire'=>'AAC', 'b_prive'=>'0', 'adresse'=>'', 'telephone'=>'242 10 22 98', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'69', 'libelle_partenaire'=>'CABINET MEDICAL DE LA MERE', 'b_prive'=>'150', 'adresse'=>'CARRIERE', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'68', 'libelle_partenaire'=>'AREA ASSURANCES', 'b_prive'=>'0', 'adresse'=>'BP 15584 DOUALA', 'telephone'=>'33438197', 'fax'=>'33438232', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'70', 'libelle_partenaire'=>'CENTRE MEDICO SOCIAL ANGE EVA', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'71', 'libelle_partenaire'=>'FONDATION MERE THERESA DU CAMEROUN', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'73', 'libelle_partenaire'=>'CENTRE MEDICAL FANTA CITRON', 'b_prive'=>'150', 'adresse'=>'MELEN', 'telephone'=>'677 35 41 48', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'74', 'libelle_partenaire'=>'MEDICAA ( MEDECINS DE FAMILLE )', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'679302160', 'fax'=>'', 'email'=>'', 'site_web'=>'KODENGUI', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'25', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'75', 'libelle_partenaire'=>'DIRECT INSURANCE SA', 'b_prive'=>'260', 'adresse'=>'BP 2028   YAOUNDE', 'telephone'=>'TEL :22651611', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'260', 'b_proforma'=>'260', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'76', 'libelle_partenaire'=>'OOOOO', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'77', 'libelle_partenaire'=>'CPAC', 'b_prive'=>'150', 'adresse'=>'BP 16344 YAOUNDE - CAMEROUN', 'telephone'=>'2222203199', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'78', 'libelle_partenaire'=>'CAMEROUN ASSISTANCE SANITAIRE', 'b_prive'=>'180', 'adresse'=>'BP 2265  DOUALA CAMEROUN', 'telephone'=>'233421414', 'fax'=>'674688814', 'email'=>'h24-ops@cas-assistance.com', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'79', 'libelle_partenaire'=>'LABORATOIRE DE YAOUNDE', 'b_prive'=>'150', 'adresse'=>'BP 11561 YDÉ', 'telephone'=>'699943130', 'fax'=>'', 'email'=>'', 'site_web'=>'www.labyaounde.org', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'20', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'80', 'libelle_partenaire'=>'SFID ( GROUPE ROUGIER )', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'81', 'libelle_partenaire'=>'HOPITAL MARIE WYSS', 'b_prive'=>'150', 'adresse'=>'NSIMEYONG', 'telephone'=>'677 39 93 75', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'0']);
 DB::table('partenaires')->insert(['id'=>'82', 'libelle_partenaire'=>'LABORATOIRE DR MANGA', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'699762568', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'83', 'libelle_partenaire'=>'CENTRE MEDICAL LE JOURDAIN', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'84', 'libelle_partenaire'=>'CENTRE MEDICAL LA CARRIÈRE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'242 03 52 52', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'20', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'85', 'libelle_partenaire'=>'SOGECAR', 'b_prive'=>'180', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'86', 'libelle_partenaire'=>'CHAMPS DE VIE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'699591745', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'87', 'libelle_partenaire'=>'SOS MEDECINS CAMEROUN', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'694 659 995', 'fax'=>'', 'email'=>'ombolofernand@yahoo.fr', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'88', 'libelle_partenaire'=>'CENTRE DE SANTE MOISE - ELISABETH', 'b_prive'=>'150', 'adresse'=>'BOCOM- MVAN', 'telephone'=>'655655702', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'20', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'89', 'libelle_partenaire'=>'MUTUELLE DU PERSONNEL D\'AFRIGROUP ( MUPAF )', 'b_prive'=>'128', 'adresse'=>'YAOUNDE', 'telephone'=>'s/c 695079921', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'128', 'b_proforma'=>'128', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'90', 'libelle_partenaire'=>'LE JOURDAIN', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'91', 'libelle_partenaire'=>'CENTRE MEDICAL VICTOIRE', 'b_prive'=>'150', 'adresse'=>'BP 4057 YAOUNDE', 'telephone'=>'222 22 36 66 /', 'fax'=>'677 49 76 45', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'92', 'libelle_partenaire'=>'ASSOCIATION SPORTIVE ET CULTURELLE HYDROCARBURES (ASCH)', 'b_prive'=>'150', 'adresse'=>'BP 955 YDE', 'telephone'=>'222 20 19 10', 'fax'=>'222 20 46 61', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'93', 'libelle_partenaire'=>'ORTHO SERVICES', 'b_prive'=>'150', 'adresse'=>'BP 35248', 'telephone'=>'222822967', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'94', 'libelle_partenaire'=>'CENTRE MEDICAL DE LA POLICE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'678 03 12 80', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'95', 'libelle_partenaire'=>'CAMRAIL', 'b_prive'=>'150', 'adresse'=>'BP 766 DOUALA', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'97', 'libelle_partenaire'=>'HOPITAL MILITAIRE DE YAOUNDE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'20', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'98', 'libelle_partenaire'=>'MUTUELLE BICEC', 'b_prive'=>'180', 'adresse'=>'BP 1925  DOUALA', 'telephone'=>'233 42 84 31', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'103', 'libelle_partenaire'=>'THAT HEALTH AGAIN ( THEA )', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'696478305', 'fax'=>'', 'email'=>'mh', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'99', 'libelle_partenaire'=>'MERLAIN CAMEROUN INC.', 'b_prive'=>'150', 'adresse'=>'BP 7966 YAOUNDE CAMEROUN', 'telephone'=>'650400491', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'100', 'libelle_partenaire'=>'CMA D\' ELIG- ESSONO', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'35', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'101', 'libelle_partenaire'=>'PARTNERS ASSURANCES', 'b_prive'=>'180', 'adresse'=>'BP 5740 DOUALA', 'telephone'=>'233 42 04 85', 'fax'=>'697 86 85 99', 'email'=>'699 68 81 92', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'102', 'libelle_partenaire'=>'STAGIAIRE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'120', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'104', 'libelle_partenaire'=>'CENTRE MEDICAL INTERNATIONAL  ( CMI )', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'698 00 71 71', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'30', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'105', 'libelle_partenaire'=>'POLYCLINIQUE INNOVA', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'694 73 56 71', 'fax'=>'', 'email'=>'', 'site_web'=>'messoumboulambert1@gmail.com', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'25', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'106', 'libelle_partenaire'=>'LABORATOIRE MODERNE DE REFERENCE', 'b_prive'=>'150', 'adresse'=>'BP 1950  YAOUNDE', 'telephone'=>'222 22 16 47', 'fax'=>'', 'email'=>'', 'site_web'=>'lamoref_1@yahoo.com', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'40', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'107', 'libelle_partenaire'=>'CEDIMER', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'108', 'libelle_partenaire'=>'LABORATOIRE DU CENTRE ( CERBA )', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'20', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'109', 'libelle_partenaire'=>'ACASSAD SANTE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'674 51 24 22', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'110', 'libelle_partenaire'=>'AGC ASSURANCES', 'b_prive'=>'180', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>1, 'b_public'=>'180', 'b_proforma'=>'180', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'111', 'libelle_partenaire'=>'POLYCLINIQUE TSINGA', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'112', 'libelle_partenaire'=>'ASSOCIATION DES FEMMES DU 1ER MINISTERE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'113', 'libelle_partenaire'=>'CLINIQUE MEDICO CHIRURGICAL REAVEN', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'116', 'libelle_partenaire'=>'CLINIQUE DE BASTOS', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'114', 'libelle_partenaire'=>'CENTRE MEDICAL LA CATHEDRALE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'115', 'libelle_partenaire'=>'HOPITAL BETHESTA', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'117', 'libelle_partenaire'=>'HOPITAL GENERAL DE YAOUNDE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'118', 'libelle_partenaire'=>'CENTRE HOSPITALIER UNIVERSITAIRE DE YDE', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'119', 'libelle_partenaire'=>'CENTRE MEDICAL  AES SONEL', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'120', 'libelle_partenaire'=>'CENTRE HOSPITALIER D\'ESSOS  ( CHE )', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'121', 'libelle_partenaire'=>'CENTRE INTEGRE DE MVAN', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'655 655 702', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'20', 'statut'=>'1']);
 DB::table('partenaires')->insert(['id'=>'122', 'libelle_partenaire'=>'CENTRE MEDICAL ARAB CONTRACTORS', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'0']);
 DB::table('partenaires')->insert(['id'=>'123', 'libelle_partenaire'=>'ARAB CONTRACTORS', 'b_prive'=>'150', 'adresse'=>'', 'telephone'=>'', 'fax'=>'', 'email'=>'', 'site_web'=>'', 'id_type_partenaire'=>2, 'b_public'=>'150', 'b_proforma'=>'150', 'reduction'=>'0', 'statut'=>'1']);
    }
}
